# Generated by Django 4.1.7 on 2023-10-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_student_pass_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pass_by',
        ),
    ]
