# Generated by Django 4.1.7 on 2023-10-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pass_by',
            field=models.CharField(max_length=50),
        ),
    ]
